# Generated by Django 6.0 on 2025-12-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='product_per_cart',
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product'), name='one_product_per_cart'),
        ),
    ]
