# Generated by Django 6.0 on 2025-12-23 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_remove_cartitem_product_per_cart_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('user',), name='one_pending_cart_per_user'),
        ),
    ]
